
services:
  postgres:
    image: postgres
    container_name: pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - myvolume:/var/lib/postgresql/data


volumes:
  myvolume:
   external: true
    